# Generated by Django 4.0.4 on 2022-05-23 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mantenimiento',
            old_name='EquioId',
            new_name='EquipoId',
        ),
    ]
